/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appqlks;

import static appqlks.QuanLi.dtm;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abmsk
 */
public class BoPhan extends javax.swing.JFrame {

    /**
     * Creates new form BoPhan
     */
    public BoPhan() {
        initComponents();
              this.setLocationRelativeTo(this);
        TableBP.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,13));
        TableBP.getTableHeader().setOpaque(false);
        TableBP.getTableHeader().setBackground(new Color(32,136,203));
        TableBP.getTableHeader().setForeground(new Color(255,255,255));
        layBP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableBP = new javax.swing.JTable();
        mbp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbp = new javax.swing.JTextField();
        luubp = new rojeru_san.RSButton();
        xoabp = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        thongbaobophan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableBP.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TableBP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Bộ Phận", "Tên Bộ Phận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableBP.setFocusable(false);
        TableBP.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableBP.setRowHeight(25);
        TableBP.setSelectionBackground(new java.awt.Color(183, 221, 251));
        TableBP.setShowVerticalLines(false);
        TableBP.getTableHeader().setReorderingAllowed(false);
        TableBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableBPMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(TableBP);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 640, 400));

        mbp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(mbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 270, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Bộ Phận");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tên Bộ Phận");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 100, -1));

        tbp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(tbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 270, 40));

        luubp.setBackground(new java.awt.Color(102, 102, 102));
        luubp.setText("LƯU");
        luubp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luubp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luubpActionPerformed(evt);
            }
        });
        jPanel1.add(luubp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 200, -1));

        xoabp.setBackground(new java.awt.Color(153, 153, 153));
        xoabp.setText("XÓA");
        xoabp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xoabp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabpActionPerformed(evt);
            }
        });
        jPanel1.add(xoabp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 200, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employee.png"))); // NOI18N
        jLabel2.setText("BỘ PHẬN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 110));

        thongbaobophan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(thongbaobophan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 730, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableBPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBPMousePressed
         dtm = (DefaultTableModel) TableBP.getModel(); 
        int i = TableBP.getSelectedRow();
        mbp.setText(dtm.getValueAt(i, 0).toString());       
        tbp.setText(dtm.getValueAt(i,1).toString()); 
    }//GEN-LAST:event_TableBPMousePressed
private void layBP() {
    
        DefaultTableModel dtm = (DefaultTableModel) TableBP.getModel();
        dtm.setNumRows(0);
        Connection ketNoi = AppQLKS.layKetNoi();
       
        String sql = "select * from BOPHAN ";
        Vector vt;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("maBP"));
                vt.add(rs.getString("tenBP"));
          
                dtm.addRow(vt);
            }
            TableBP.setModel(dtm);
            rs.close();
            ps.close();
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void LuuBP(String MBP,String TBP) {
        Connection ketNoi = AppQLKS.layKetNoi();
        String sql = "insert into BOPHAN values (?,?) ";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, MBP);
            ps.setString(2, TBP);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



private int kiemTraBP(String MBP) {
        Connection ketNoi = AppQLKS.layKetNoi();
        int tonTai = 0;
        String sql = "select * from BOPHAN where maBP ='" + MBP + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            ketNoi.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        return tonTai;
    }
    private void SuaBP(String MBP) {
        Connection ketNoi = AppQLKS.layKetNoi();
        
        String sql = "update BOPHAN set tenBP=N'"+tbp.getText()+"'where maHP='"+MBP+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   private void xoaBP(String MBP) {
        Connection ketNoi = AppQLKS.layKetNoi();
        String sql = "delete from BOPHAN where maBP = ?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, MBP);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void luubpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luubpActionPerformed
        String MBP=mbp.getText();
        String TBP=tbp.getText();
        int temp0=0,temp1=0;
        int check=kiemTraBP(MBP);

        if(MBP.equals("")){
            temp0=1;
            thongbaobophan.setForeground(Color.RED);
            thongbaobophan.setText("Mã Không Được Bỏ Trống ");
        }
        else if(TBP.equals("")){
            temp1=1;
            thongbaobophan.setForeground(Color.RED);
            thongbaobophan.setText("Tên  Không Được Bỏ Trống ");
        }

        else if(temp0!=1 &&temp1!=1 ){
            if(check==1){
                SuaBP(MBP);
                layBP();
                thongbaobophan.setForeground(Color.BLUE);
                thongbaobophan.setText("Sửa Thành Công ");
            }
            else{
                LuuBP(MBP,TBP);
                thongbaobophan.setForeground(Color.BLUE);
                thongbaobophan.setText("Lưu Thành Công ");
                layBP();
            }
        }
    }//GEN-LAST:event_luubpActionPerformed

    private void xoabpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabpActionPerformed
        String MBP =mbp.getText();
        int check;
        int kiemTra = 0;
        if (MBP.equals("")) {
            kiemTra = 1;
            JOptionPane.showMessageDialog(this, "Hãy nhập Mã  bạn muốn xóa");
        }
        else if (kiemTra != 1) {
            check = kiemTraBP(MBP);
            if (check == 1) {

                int ret = JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Muốn Xóa?", "Xác Nhận", 0);
                if(ret == JOptionPane.CANCEL_OPTION)
                return;
                else  if(ret == JOptionPane.OK_OPTION)
                {
                    xoaBP(MBP);
                    JOptionPane.showMessageDialog(this, "Xóa  thành công");
                    this.layBP();

                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Mã Chưa Có");
            }
        }
    }//GEN-LAST:event_xoabpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoPhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojeru_san.RSButton luubp;
    private javax.swing.JTextField mbp;
    private javax.swing.JTextField tbp;
    private javax.swing.JLabel thongbaobophan;
    private rojeru_san.RSButton xoabp;
    // End of variables declaration//GEN-END:variables
}
