/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appqlks;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abmsk
 */
public class DangKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        this.setLocation(350,20);
      
        loadComboBox();
        Date date=new Date();
        ngaysinh.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JTextField();
        rematkhau = new javax.swing.JPasswordField();
        dangky = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        matkhau = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        diachi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sdt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phai = new javax.swing.JComboBox<>();
        mabp = new javax.swing.JComboBox<>();
        tenbp = new javax.swing.JLabel();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 0, 153));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("ĐĂNG KÝ TÀI KHOẢN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 46));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("TÀI KHOẢN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 20));

        taikhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taikhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 380, 25));

        rematkhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rematkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(rematkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 380, 25));

        dangky.setBackground(new java.awt.Color(255, 255, 255));
        dangky.setkBorderRadius(50);
        dangky.setkEndColor(new java.awt.Color(51, 51, 51));
        dangky.setkStartColor(new java.awt.Color(204, 204, 204));
        dangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dangkyMousePressed(evt);
            }
        });
        dangky.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ĐĂNG KÝ");
        dangky.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 40));

        jPanel1.add(dangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 840, 150, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("NHẬP LẠI MẬT KHẨU");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 235, 160, 30));

        matkhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 380, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("MẬT KHẨU");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("TÊN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 40, 30));

        ten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });
        jPanel1.add(ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 380, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("PHÁI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 50, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("NGÀY SINH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 111, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("ĐỊA CHỈ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 70, 30));

        diachi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diachi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 380, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("SĐT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 70, 30));

        sdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 380, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("EMAIL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 70, 30));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 153, 255)));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 380, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("MÃ BỘ PHẬN");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 100, 30));

        phai.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        phai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel1.add(phai, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 160, 30));

        mabp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mabp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mabpItemStateChanged(evt);
            }
        });
        mabp.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                mabpPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        mabp.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mabpMouseWheelMoved(evt);
            }
        });
        jPanel1.add(mabp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 780, 160, 30));

        tenbp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tenbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 780, 140, 30));

        ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 380, 25));

        kGradientPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 450, 900));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PHẦN MỀM QUẢN LÍ KHÁCH SẠN");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 310, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void loadComboBox()
    {
        Connection ketNoi = AppQLKS.layKetNoi();
        String query = "SELECT  maBP FROM BOPHAN";
        try
        {
            Statement sta = ketNoi.createStatement();
            ResultSet ketQua = sta.executeQuery(query);
            while(ketQua.next())
            {
                
                mabp.addItem(ketQua.getString("maBP"));                
            }            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }    
    private void Luu(String id,String pass,String isActive,String isAdmin,String isAllowed,
     String ten,int phai,String ngaysinh,String diachi,String sdt,String email,String mabp) {
        Connection ketNoi = AppQLKS.layKetNoi();
        String sql = "insert into NHANVIEN values (?,?,?,?,?,?,?,?,?,?,?,?) ";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, id);
            ps.setString(2, pass);
            ps.setString(3, isActive);
            ps.setString(4, isAdmin);
            ps.setString(5, isAllowed);
            ps.setString(6, ten);
            ps.setInt(7, phai);
            ps.setString(8, ngaysinh);
            ps.setString(9, diachi);
            ps.setString(10, sdt);
            ps.setString(11, email);
            ps.setString(12, mabp);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int kiemTra(String user){
        Connection ketNoi= AppQLKS.layKetNoi();
        int tonTai=0;
        String sql="select * from NHANVIEN where username='"+user+"'";
      
        try{
            PreparedStatement ps=ketNoi.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                tonTai=1;
            }
            rs.close();
            ps.close();
            ketNoi.close();
            
        }
        catch( SQLException ex){
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null,ex);
        }
        return tonTai;
    }
    private void dangkyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkyMousePressed
        String id=taikhoan.getText();
        String passwd=matkhau.getText();
        String repasswd=rematkhau.getText();
        String TEN=ten.getText();
        String DIACHI=diachi.getText();
        String SDT=sdt.getText();
        String EMAIL=email.getText();
        int gioitinh=0;
        if(phai.getSelectedIndex()==0) {
            gioitinh=1;
        }
        else gioitinh=0;
        int check;
        String regex="\\w+@\\w+\\.\\w+";
        String pattern="0[0-9]{9}";
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        String ns=df.format(ngaysinh.getDate());
        String BP = (String)mabp.getSelectedItem();  
        int temp0=0,temp1=0,temp2=0,temp3=0,temp4=0,temp5=0;
        if(id.equals("")){
            temp0=1;
            JOptionPane.showMessageDialog(this, "Tài Khoản Không Được Bỏ Trống");
        }
        else if(passwd.equals("")){
            temp1=1;
            JOptionPane.showMessageDialog(this, "Mật Khẩu Không Được Bỏ Trống");
        }
        else if(!repasswd.equalsIgnoreCase(passwd)){
            JOptionPane.showMessageDialog(this, "Hai Mật Khẩu Phải Trùng Nhau");
        }
        else if(TEN.equals("")){
            temp2=1;
            JOptionPane.showMessageDialog(this, "Tên Không Được Bỏ Trống");
        }
        else if(DIACHI.equals("")){
            temp3=1;
            JOptionPane.showMessageDialog(this, "Địa Chỉ Không Được Bỏ Trống");
        }

        else if(SDT.equals("")){
            temp4=1;
            JOptionPane.showMessageDialog(this, "SĐT Không Được Bỏ Trống");
        }
        else if(!SDT.matches(pattern)){
            JOptionPane.showMessageDialog(this, "SĐT Không Hợp Lệ");
        }
        else if(EMAIL.equals("")){
            temp5=1;
            JOptionPane.showMessageDialog(this, "Email Không Được Bỏ Trống");
        }
        else if(!EMAIL.matches(regex)){
            JOptionPane.showMessageDialog(this, "Email Không Hợp Lệ");
        }
        else if(temp0!=1 &&temp1!=1 &&temp2!=1 &&temp3!=1&& temp4!=1&& temp5!=1){
            check=kiemTra(id);
            if(check==1){
                JOptionPane.showMessageDialog(this, "Tài Khoản Đã Có Người Sử Dụng");
            }
            else{
                Luu( id,passwd, "1", "0", "0", TEN, gioitinh,ns,DIACHI,SDT,EMAIL,BP);
                JOptionPane.showMessageDialog(this, "Đăng Ký Thành Công");
            }
            
            

        }
    }//GEN-LAST:event_dangkyMousePressed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenActionPerformed

    private void mabpMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mabpMouseWheelMoved
   
    }//GEN-LAST:event_mabpMouseWheelMoved

    private void mabpPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_mabpPopupMenuWillBecomeInvisible
  
    }//GEN-LAST:event_mabpPopupMenuWillBecomeInvisible

    private void mabpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mabpItemStateChanged
                Connection ketNoi = AppQLKS.layKetNoi();
        String sql="SELECT * FROM BOPHAN WHERE maBP=?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1,(String)this.mabp.getSelectedItem());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                this.tenbp.setText(rs.getString("tenBP"));
            }
            rs.close();
            ps.close();

        }
        catch (SQLException ex) {
            Logger.getLogger(DangKy.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_mabpItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel dangky;
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JComboBox<String> mabp;
    private javax.swing.JPasswordField matkhau;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JComboBox<String> phai;
    private javax.swing.JPasswordField rematkhau;
    private javax.swing.JTextField sdt;
    private javax.swing.JTextField taikhoan;
    private javax.swing.JTextField ten;
    private javax.swing.JLabel tenbp;
    // End of variables declaration//GEN-END:variables
}
