/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appqlks;

import static appqlks.QuanLi.dtm;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abmsk
 */
public class QuanLiNguoiDung extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiNguoiDung
     */
    public QuanLiNguoiDung() {
        initComponents();
        this.setLocationRelativeTo(this);
        TableNguoiDung.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,13));
        TableNguoiDung.getTableHeader().setOpaque(false);
        TableNguoiDung.getTableHeader().setBackground(new Color(32,136,203));
        TableNguoiDung.getTableHeader().setForeground(new Color(255,255,255));
        layNguoiDung();
    }
  

private int kiemTraTK(String TK) {
        Connection ketNoi = AppQLKS.layKetNoi();
        int tonTai = 0;
        String sql = "select * from NHANVIEN where username ='" + TK + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            ketNoi.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        return tonTai;
    }
    private void CapQuyen(String TK) {
        Connection ketNoi = AppQLKS.layKetNoi();
        
        String sql = "update NHANVIEN set isAllowed='1' where username='"+TK+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private void xoaNV(String TK) {
        Connection ketNoi = AppQLKS.layKetNoi();
        String sql = "update NHANVIEN set isActive='0' where username='"+TK+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
     private void capnhatMK(String TK) {
        Connection ketNoi = AppQLKS.layKetNoi();
        String sql = "update NHANVIEN set pw='123' where username='"+TK+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }      
private void layNguoiDung() {
    
        DefaultTableModel dtm = (DefaultTableModel) TableNguoiDung.getModel();
        dtm.setNumRows(0);
        Connection ketNoi = AppQLKS.layKetNoi();
       
        String sql = "select * from NHANVIEN ";
        Vector vt;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("username"));
                 vt.add(rs.getString("ten"));
                vt.add(rs.getString("isActive"));
                vt.add(rs.getString("isAdmin"));
                vt.add(rs.getString("isAllowed"));
                dtm.addRow(vt);
            }
            TableNguoiDung.setModel(dtm);
            rs.close();
            ps.close();
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(NewMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNguoiDung = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        hoatdong = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quanli = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JLabel();
        quyen = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tenNV = new javax.swing.JLabel();
        luu = new rojeru_san.RSButton();
        xoa = new rojeru_san.RSButton();
        capnhat = new rojeru_san.RSButton();
        thongbaonv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/oil.png"))); // NOI18N
        jLabel2.setText("QUẢN LÍ NGƯỜI DÙNG");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 70));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 110));

        TableNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TableNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tài Khoản", "Tên", "Hoạt Động", "Quyền", "Quản Lí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableNguoiDung.setFocusable(false);
        TableNguoiDung.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableNguoiDung.setRowHeight(25);
        TableNguoiDung.setSelectionBackground(new java.awt.Color(183, 221, 251));
        TableNguoiDung.setShowVerticalLines(false);
        TableNguoiDung.getTableHeader().setReorderingAllowed(false);
        TableNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableNguoiDungMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TableNguoiDung);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 880, 540));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tài Khoản");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, -1, -1));

        hoatdong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hoatdong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jPanel3.add(hoatdong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 270, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Hoạt Động");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Quyền");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, -1, -1));

        quanli.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        quanli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jPanel3.add(quanli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Quản Lí");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, -1, -1));

        taikhoan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, 150, 40));

        quyen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        quyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jPanel3.add(quyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, 150, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên NV");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, -1));

        tenNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 150, 40));

        luu.setBackground(new java.awt.Color(51, 51, 51));
        luu.setText("CẤP QUYỀN");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });
        jPanel3.add(luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 510, -1, -1));

        xoa.setBackground(new java.awt.Color(153, 153, 153));
        xoa.setText("XÓA ");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel3.add(xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, -1, -1));

        capnhat.setBackground(new java.awt.Color(0, 153, 153));
        capnhat.setText("CẬP NHẬT MẬT KHẨU");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });
        jPanel3.add(capnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, -1, -1));

        thongbaonv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(thongbaonv, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableNguoiDungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNguoiDungMousePressed
         dtm = (DefaultTableModel) TableNguoiDung.getModel(); 
        int i = TableNguoiDung.getSelectedRow();
        taikhoan.setText(dtm.getValueAt(i, 0).toString());       
        tenNV.setText(dtm.getValueAt(i,1).toString()); 
        
        hoatdong.setSelectedItem(dtm.getValueAt(i, 2).toString());
        quyen.setSelectedItem(dtm.getValueAt(i, 3).toString());
        quanli.setSelectedItem(dtm.getValueAt(i, 4).toString());
    }//GEN-LAST:event_TableNguoiDungMousePressed

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
       CapQuyen(taikhoan.getText());
        thongbaonv.setForeground(Color.BLUE);
             thongbaonv.setText("Thành Công ");
             this.layNguoiDung();
    }//GEN-LAST:event_luuActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        xoaNV(taikhoan.getText());
        thongbaonv.setForeground(Color.BLUE);
        thongbaonv.setText("Thành Công ");
         this.layNguoiDung();
    }//GEN-LAST:event_xoaActionPerformed

    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
         capnhatMK(taikhoan.getText());
        thongbaonv.setForeground(Color.BLUE);
        thongbaonv.setText("Thành Công ");
         this.layNguoiDung();
    }//GEN-LAST:event_capnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiNguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNguoiDung;
    private rojeru_san.RSButton capnhat;
    private javax.swing.JComboBox<String> hoatdong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton luu;
    private javax.swing.JComboBox<String> quanli;
    private javax.swing.JComboBox<String> quyen;
    private javax.swing.JLabel taikhoan;
    private javax.swing.JLabel tenNV;
    private javax.swing.JLabel thongbaonv;
    private rojeru_san.RSButton xoa;
    // End of variables declaration//GEN-END:variables
}
